server_port: "8081"
close_timeout: "5s"
db_dsn: "host=localhost port=5432 user=postgres password=postgres dbname=zdravoshag sslmode=disable"
grpc_core_users: "localhost:5001"
grpc_core_health: "localhost:5002"
nats_url: "nats://localhost:4222"
tracer_host: "localhost"
tracer_port: "4317"
service_name: "public-tg-bot"
tg_bot_token: ""
tg_webhook_host: "https://bot.zdravoshag.ru"
jwt_secret: "change-me-to-a-long-random-string"
