config:
  server_port:
    type: int
    default: "8081"
    source: yaml
  close_timeout:
    type: duration
    default: "5s"
    source: yaml
  db_dsn:
    type: string
    default: "host=localhost port=5432 user=postgres password=postgres dbname=zdravoshag sslmode=disable"
    source: yaml
  grpc_core_users:
    type: string
    default: "localhost:5001"
    source: yaml
  grpc_core_health:
    type: string
    default: "localhost:5002"
    source: yaml
  nats_url:
    type: string
    default: "nats://localhost:4222"
    source: yaml
  tracer_host:
    type: string
    default: "localhost"
    source: yaml
  tracer_port:
    type: string
    default: "4317"
    source: yaml
  service_name:
    type: string
    default: "public-tg-bot"
    source: yaml
  tg_bot_token:
    type: string
    default: ""
    source: env
  tg_webhook_host:
    type: string
    default: "https://bot.zdravoshag.ru"
    source: yaml
  site_url:
    type: string
    default: ""
    source: yaml
  jwt_secret:
    type: string
    default: "change-me"
    source: env
